//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.23 at 05:22:53 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.osoa.org/xmlns/sca/1.0",
									 xmlns={@XmlNs(namespaceURI = "http://www.osoa.org/xmlns/sca/1.0", prefix = "sca"),
											@XmlNs(namespaceURI = "http://www.omg.org/XMI", prefix = "xmi"),
											@XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema-instance", prefix = "xsi"),
											@XmlNs(namespaceURI = "http://xsd.tns.tibco.com/amf/models/sca/implementationtype/BW", prefix = "BW"),
											@XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema", prefix = "XMLSchema"),
											@XmlNs(namespaceURI = "http://schemas.tibco.com/amx/3.0/compositeext", prefix = "compositeext"),
											@XmlNs(namespaceURI = "http://xsd.tns.tibco.com/amf/models/sca/extensions", prefix = "scaext")
											},
									 elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.osoa.xmlns.sca._1;

import javax.xml.bind.annotation.XmlNs;
