//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 10:38:48 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.tibco.com/tra/model/core/PackagingModel",
									 xmlns={@XmlNs(namespaceURI = "http://schemas.tibco.com/tra/model/core/PackagingModel", prefix = "packaging"),
											@XmlNs(namespaceURI = "http://www.w3.org/2001/XMLSchema", prefix = "xsd")},
									 elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tibco.schemas.tra.model.core.packagingmodel;

import javax.xml.bind.annotation.XmlNs;
