//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 10:59:25 AM CET 
//


package com.tibco.tns.xsd.amf.models.sca.extensions;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tibco.tns.xsd.amf.models.sca.extensions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Implementation_QNAME = new QName("http://xsd.tns.tibco.com/amf/models/sca/extensions", "implementation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tibco.tns.xsd.amf.models.sca.extensions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Implementation }
     * 
     */
    public Implementation createImplementation() {
        return new Implementation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Implementation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xsd.tns.tibco.com/amf/models/sca/extensions", name = "implementation")
    public JAXBElement<Implementation> createImplementation(Implementation value) {
        return new JAXBElement<Implementation>(_Implementation_QNAME, Implementation.class, null, value);
    }

}
