//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 10:59:25 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xsd.tns.tibco.com/amf/models/sca/extensions",
									 xmlns={@XmlNs(namespaceURI = "http://xsd.tns.tibco.com/amf/models/sca/extensions", prefix = "scaext")},
									 elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

package com.tibco.tns.xsd.amf.models.sca.extensions;

import javax.xml.bind.annotation.XmlNs;
