//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.16 at 07:21:33 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tibco.com/xmlns/repo/types/2002",
									 xmlns={@XmlNs(namespaceURI = "http://www.tibco.com/xmlns/repo/types/2002", prefix = "")},
									 elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tibco.xmlns.repo.types._2002;

import javax.xml.bind.annotation.XmlNs;
